services:
  - type: worker
    name: jarvis-bot
    env: docker
    plan: starter
    dockerfilePath: Dockerfile
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OWNER
        sync: false
